#!/bin/sh
#	Rubyripper launcher
#	(C) 2007-2010 SliTaz - GNU General Public License v3. 

RUBY_GTK2_PC=$(/usr/bin/pkg-config --exists ruby-gtk2)
if [ $RUBY_GTK2_PC ]; then
	/usr/bin/rrip_gui
else
	/usr/bin/xterm -T "Rubyripper CLI" -e /usr/bin/rrip_cli
fi
