#!/bin/sh

mysqldump postfix > /dev/null 2>&1 || mysql <<EOT
CREATE DATABASE postfix;
CREATE USER 'postfix'@'localhost' IDENTIFIED BY 'postfix';
GRANT ALL PRIVILEGES ON `postfix` . * TO 'postfix'@'localhost';
EOT

chmod -x /etc/mysql.d/postfixadmin
