# SliTaz desktopbox messages.

CHARS_SIZE="72"
NEW_FOLDER_LABEL="Criar uma nova pasta no desktop:"
FOLDER_ENTRY_MSG="pasta"
NEW_FILE_LABEL="Criar um novo arquivo no desktop:"
FILE_ENTRY_MSG="arquivo"
ADD_ICON_LABEL="Adiciona ícones ao desktop"
DESKTOP_DIALOG_TAZUSB="Salva o sistema de arquivo usando compressão"
DESKTOP_DIALOG_LABEL="Finalizar sessão, reiniciar ou desligar o sistema"
DESKTOP_LOGOUT_BUTTON="Finalizar Sessão"
DESKTOP_SHUTDOWN_BUTTON="Desligar Computador"
DESKTOP_REBOOT_BUTTON="Reiniciar Sistema"
