#!/bin/sh
# /etc/init.d/ajaxterm : Start, stop and restart AjaxTerm server on SliTaz, at
# boot time or with the command line.
#
# To start AjaxTerm server at boot time, just put ajaxterm in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=AjaxTerm
DESC="$(_ '%s server' AjaxTerm)"
DAEMON="/usr/share/ajaxterm/ajaxterm.py"
OPTIONS=$AJAXTERM_OPTIONS
PIDFILE=/var/run/ajaxterm.pid
[ -n "$OPTIONS" ] || OPTIONS="--pidfile $PIDFILE --daemon --port=8022 --command=/usr/share/ajaxterm/login"
export PYTHONPATH=/usr/share/ajaxterm

case "$1" in
  start)
    if active_pidfile $PIDFILE python ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS
    status
    sleep 2
    ;;
  stop)
    if ! active_pidfile $PIDFILE python ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    status
    rm -f $PIDFILE
    sleep 2
    ;;
  restart)
    if ! active_pidfile $PIDFILE python ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Restarting %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    rm -f $PIDFILE
    sleep 2
    $DAEMON $OPTIONS
    status
    sleep 2
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
