#!/bin/sh
# /etc/init.d/daemon-name: Start, stop and restart daemon
# on SliTaz, at boot time or with the command line.
#
# To start daemon at boot time, just put the right name in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf.
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=Privoxy
DESC="$(_ 'Web proxy daemon')"
DAEMON=/usr/sbin/privoxy
OPTIONS="--pidfile /var/run/privoxy.pid"
USER="--user privoxy"
CONFIG=/etc/privoxy/config
PIDFILE=/var/run/privoxy.pid

case "$1" in
  start)
    if active_pidfile $PIDFILE privoxy ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS $USER $CONFIG 2>/dev/null
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE privoxy ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    rm $PIDFILE
    status
    ;;
  restart)
    if ! active_pidfile $PIDFILE privoxy ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    kill $(cat $PIDFILE)
    rm $PIDFILE
    sleep 2
    action 'Restarting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS $USER $CONFIG 2>/dev/null
    status
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
