#!/bin/sh -e

if test $(id -u) != 0 ; then
	echo -e "\nYou must be root to run `basename $0`."
	echo -e "Please type 'su' and root password to become super-user.\n"
	exit 0
fi

if [ -d /var/lib/tazpkg/installed/skype ]; then
  tazpkg remove skype
  [ -d /var/lib/tazpkg/installed/skype ] && exit 1
fi
[ -d /usr/share/skype ] && rm -rf /usr/share/skype

# Download tarball
WEB_SITE="http://www.skype.com/"
wget ${WEB_SITE}go/getskype-linux-static

# Extract
TARBALL=$(ls getskype-linux-static skype*.tar.bz2 2> /dev/null || true)
tar xjf $TARBALL
VERSION=$(ls -d skype_static-*/)
VERSION=${VERSION%/}
VERSION=${VERSION#skype_static-}
cd skype_static-$VERSION

# Install files
mkdir -p /usr/share/skype
mv */ LICENSE README /usr/share/skype
mv skype /usr/bin
mv skype.conf /etc
mv skype.desktop /usr/share/applications
ln /usr/share/skype/icons/*16.png /usr/share/pixmaps/skype.png

# Create pseudo package
while read file; do
	dest=skype-$VERSION/fs$(dirname $file)
	[ -d $dest ] || mkdir -p $dest
	cp -a $file $dest
done <<EOT
/usr/bin/skype
/etc/skype.conf
/usr/share/applications/skype.desktop
/usr/share/pixmaps/skype.png
/usr/share/skype
EOT
cat > skype-$VERSION/receipt <<EOT
PACKAGE="skype"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="Skype Internet Telephony."
WEB_SITE="$WEB_SITE"
DEPENDS="libsigc++ xorg-libXv xorg-libXss"
CONFIG_FILES="/etc/skype.conf"
EOT

# Pack
tazpkg pack skype-$VERSION

# Install pseudo package
tazpkg install skype-$VERSION.tazpkg
cd ..

# Clean
rm -rf skype_static-$VERSION* $TARBALL
