#!/bin/sh

WEB_SITE="https://github.com/BaRRaKudaRain/PCem-ROMs"
ARCHIVE="https://github.com$(wget -O - $WEB_SITE/releases | sed '/.tar.gz/!d;s|.*href="||;s|" .*||;q')"

mv -f /home/$USER/.pcem/roms /home/$USER/.pcem/roms-old ||
mkdir -p /home/$USER/.pcem
wget -O - $ARCHIVE | tar xzf - -C /home/$USER/.pcem/
mv /home/$USER/.pcem/PCem-ROMs-* /home/$USER/.pcem/roms
chown -R $USER.users /home/$USER/.pcem
