<?php
#
# File generated by Dolibarr installer 3.0.0 on 2011-07-03 17:32:29
#
# Take a look at conf.php.example file for an example of conf.php file
# and explanations for all possibles parameters.
#
$dolibarr_main_url_root='http://localhost/dolibarr';
$dolibarr_main_document_root='/usr/share/dolibarr/htdocs';
$dolibarr_main_data_root='/var/lib/dolibarr/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_user='dolibarr';
$dolibarr_main_db_pass='dolibarr';
$dolibarr_main_db_type='mysql';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

# Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='3d0b47c788fd906624931e35dc9bf072';
$dolibarr_mailing_limit_sendbyweb='0';
?>
