#!/bin/sh -e

ROOT="$1"
PACKAGE="unace"
WEB_SITE="http://www.winace.com/"
WGET_URL="${WEB_SITE}news.html"


if test $(id -u) != 0 ; then
	echo -e "\nYou must be root to run `basename $0`."
	echo -e "Please type 'su' and root password to become super-user.\n"
	exit 0
fi

if [ -d $ROOT/var/lib/tazpkg/installed/$PACKAGE ]; then
  [ -n "$ROOT" ] && exit 1
  tazpkg remove $PACKAGE
  [ -d /var/lib/tazpkg/installed/$PACKAGE ] && exit 1
fi

WGET_URL=$(wget -O - $WGET_URL | grep 'linunace' | sed 's/.*href="\(.*z\)".*/\1/')
TARBALL=$(basename $WGET_URL || true)
VERSION=$(echo $TARBALL | sed 's/.*linunace\(.*\).t.*/\1/')
echo "Downloading $PACKAGE $VERSION from $WGET_URL..."

BASE=$PWD
DIR=/tmp/$0-$$
mkdir -p $DIR
cd $DIR

# Download tarball
wget $WGET_URL
if [ ! -f $TARBALL ]; then
	cd $BASE
	rm -rf $DIR
	echo "Could not download $TARBALL. Exiting."
	exit 1
fi

# Extract
busybox tar xf $TARBALL

# extracted pkg can be removed: Save RAM before packing
rm -rf $TARBALL

# Install files
dir=$PACKAGE-$VERSION/fs/usr/bin
mkdir -p $dir
mv unace $dir

# Create pseudo package
cat > $PACKAGE-$VERSION/receipt <<EOT
PACKAGE="$PACKAGE"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="An archive unpacker."
WEB_SITE="$WEB_SITE"
EOT

# Pack
tazpkg pack $PACKAGE-$VERSION

# Clean to save RAM memory
rm -rf $PACKAGE-$VERSION

# Install pseudo package
tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT
cd $BASE

# Clean
rm -rf $DIR

