#!/bin/sh 

# Get and install FoxitReader for Linux

PACKAGE="FoxitReader"
VERSION="1.1-0"
RPMPKG="$PACKAGE-$VERSION.fc9.i386.rpm"
URL="http://cdn01.foxitsoftware.com/pub/foxit/reader/desktop/linux/1.x/1.1/enu/$RPMPKG"
CUR_DIR=$(pwd)
TEMP_DIR=/tmp/$PACKAGE-$VERSION-$$
ROOT="$1"

# Check if we are root
if test $(id -u) != 0 ; then
    echo -e "\nYou must be root to run `basename $0`."
    echo -e "Please type 'su' and root password to become super-user.\n"
    exit 1
fi

# Avoid reinstall
if [ -d $ROOT/var/lib/tazpkg/installed/$PACKAGE ]; then
    echo -e "\n$PACKAGE package is already installed.\n"
    exit 1
fi

# Create a TEMP_DIR
mkdir $TEMP_DIR
cd $TEMP_DIR

# Download the file
wget $URL 
if [ ! -f $RPMPKG ]; then
	cd $CUR_DIR
	rm -rf $TEMP_DIR
	echo "Could not download $RPMPKG. Exiting."
	exit 1
fi

rpm2cpio $RPMPKG | cpio -dium

# extracted pkg can be removed: Save RAM
rm -rf $RPMPKG

mkdir -p $PACKAGE-$VERSION/fs
mv $TEMP_DIR/usr $PACKAGE-$VERSION/fs
cd $PACKAGE-$VERSION/fs/usr/share/applications/ && mv fedora-Foxit-Reader.desktop Foxit-Reader.desktop

cd $TEMP_DIR

cat > $PACKAGE-$VERSION/receipt << EOT
PACKAGE="$PACKAGE"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="A free PDF document viewer for the Linux platform."
DEPENDS="gtk+ libcups"
WEB_SITE="http://www.foxitsoftware.com/pdf/desklinux/"
EOT

# Pack
tazpkg pack $PACKAGE-$VERSION gzip

# Clean to save RAM memory
rm -rf $PACKAGE-$VERSION

# Install pseudo package
yes y | tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT

# Clean
cd $CUR_DIR
rm -rf $TEMP_DIR
