# SliTaz desktopbox messages.

CHARS_SIZE="72"
NEW_FOLDER_LABEL="Créer un nouveau dossier sur le bureau:"
FOLDER_ENTRY_MSG="dossier"
NEW_FILE_LABEL="Créer un nouveau fichier sur le bureau:"
FILE_ENTRY_MSG="fichier"
ADD_ICON_LABEL="Ajouter des icônes de bureau"
DESKTOP_DIALOG_TAZUSB="Enregistrer le système avec la compression"
DESKTOP_DIALOG_LABEL="Déconnexion, arrêt ou redémarrage du système"
DESKTOP_LOGOUT_BUTTON="Fermer la session X"
DESKTOP_SHUTDOWN_BUTTON="Eteindre le système"
DESKTOP_REBOOT_BUTTON="Redémarrer le système"
