#!/bin/sh
# /etc/init.d/nagios : Start, stop and restart ICAP server on SliTaz, at 
# boot time or with the command line.
#
# To start ICAP server at boot time, just put c-icapd in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=c-icap
DESC="ICAP Server"
DAEMON=/usr/bin/c-icap
OPTIONS=""
PIDFILE=/var/run/c-icap/c-icap.pid

case "$1" in
  start)
    if active_pidfile $PIDFILE $NAME ; then
      echo "$NAME already running."
      exit 1
    fi
    echo -n "Starting $DESC: $NAME... "
	$DAEMON $OPTIONS
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE $NAME ; then
      echo "$NAME is not running."
      exit 1
    fi
    echo -n "Stopping $DESC: $NAME... "
    kill `cat $PIDFILE`
    status
    ;;
  restart|reload)
    if ! active_pidfile $PIDFILE $NAME ; then
      echo "$NAME is not running."
      exit 1
    fi
    echo -n "Restarting $DESC: $NAME... "
    kill `cat $PIDFILE`
    sleep 2
    $DAEMON $OPTIONS
    status
    ;;
  test)
	configtest ;;
  *)
    echo ""
    echo -e "\033[1mUsage:\033[0m /etc/init.d/`basename $0` [start|stop|restart|reload]"
    echo ""
    exit 1
    ;;
esac

exit 0
