#!/bin/sh
# /etc/init.d/dnsmasq: Start, stop and restart DNSmasq daemon on SliTaz, at boot
# time or with the command line.
#
# To start daemon at boot time, just put the right name in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf.
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=DNSmasq
DESC="$(_ '%s daemon' dnsmasq)"
DAEMON=/usr/sbin/dnsmasq
OPTIONS=$DNSMASQ_OPTIONS
PIDFILE=/var/run/dnsmasq.pid

case "$1" in
  start)
    if active_pidfile $PIDFILE dnsmasq ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE dnsmasq ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    rm $PIDFILE
    status
    ;;
  restart)
    if ! active_pidfile $PIDFILE dnsmasq ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Restarting %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    rm $PIDFILE
    sleep 2
    $DAEMON $OPTIONS
    status
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
