--- mISDNuser-1_1_7_2/Makefile
+++ mISDNuser-1_1_7_2/Makefile
@@ -13,7 +13,7 @@
 # Change this to create an install prefix for the shared libs, programms and
 # includes
 #
-INSTALL_PREFIX := /
+INSTALL_PREFIX := $(DESTDIR)
 export INSTALL_PREFIX
 
 MISDNINCLUDEDIR := $(MISDNDIR)/include
