#!/bin/sh
# /etc/init.d/gpm : Start, stop and restart gpm server on SliTaz, at
# boot time or with the command line.
#
# To start gpm server at boot time, just put mysql in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=gpm
DESC="$(_ '%s server' GPM)"
DAEMON=/usr/sbin/gpm
OPTIONS=$GPM_OPTIONS
[ -n "$OPTIONS" ] || OPTIONS="-m /dev/psaux -t ps2"

case "$1" in
  start)
    if active_pidfile $PIDFILE gpm ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE gpm ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    $DAEMON -k
    status
    ;;
  restart)
    if ! active_pidfile $PIDFILE gpm ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Restarting %s: %s...' "$DESC" $NAME
    $DAEMON -k
    status
    $DAEMON $OPTIONS
    status
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
