#!/bin/sh
# /etc/init.d/dropbear : Start, stop and restart SSH server on SliTaz, at
# boot time or with the command line.
#
# To start SSH server at boot time, just put dropbear in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=Dropbear
DESC="$(_ '%s server' SSH)"
DAEMON=/usr/sbin/dropbear
OPTIONS=$DROPBEAR_OPTIONS
PIDFILE=/var/run/dropbear.pid

case "$1" in
  start)
    # We need rsa and dss host key file to start dropbear.
    if [ ! -s /etc/dropbear/dropbear_rsa_host_key ] ; then
      action 'Generating Dropbear %s key...' RSA
      # Need to delete key before creating it.
      rm -f /etc/dropbear/dropbear_rsa_host_key
      dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null 2>&1
      status
    fi
    if [ ! -s /etc/dropbear/dropbear_dss_host_key ] ; then
      action 'Generating Dropbear %s key...' DSS
      # Need to delete key before creating it.
      rm -f /etc/dropbear/dropbear_dss_host_key
      dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key >/dev/null 2>&1
      status
    fi
    if active_pidfile $PIDFILE dropbear ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE dropbear ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    status
    ;;
  restart)
    if ! active_pidfile $PIDFILE dropbear ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Restarting %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE)
    sleep 2
    $DAEMON $OPTIONS
    status
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
