#!/bin/sh -e
: ${DIALOG=tazdialog}

ROOT="$1"

if test $(id -u) != 0 ; then
	echo -e "\nYou must be root to run `basename $0`."
	echo -e "Please type 'su' and root password to become super-user.\n"
	exit 0
fi

if [ -d $ROOT/var/lib/tazpkg/installed/flash-plugin ]; then
  [ -n "$ROOT" ] && exit 1
  tazpkg remove flash-plugin
  [ -d /var/lib/tazpkg/installed/flash-plugin ] && exit 1
fi
WEB_SITE="http://www.adobe.com/products/flash/"
URL="http://fpdownload.macromedia.com/get/flashplayer/current/"

# Download tarball
VERSIONS=""; i=9; while true; do
  if wget -s ${URL}install_flash_player_${i}_linux.tar.gz 2> /dev/null; then
    VERSIONS="$VERSIONS $i"
    [ -n "$ROOT" ] && break
  elif [ -n "$VERSIONS" ]; then
    break
  elif [ $i -gt 20 ]; then
    exit 1
  fi
  i=$(($i + 1))
done

value="$(echo $VERSIONS)"
case "$VERSIONS" in
*[0-9]\ [1-9]*)
	exec 3>&1
	value=`$DIALOG --clear --colors --title " Install Flash plugin " \
		--menu  "Which version to install" 16 70 5 \
		$(for i in $VERSIONS; do echo $i; echo "flash-$i"; done) \
		2>&1 1>&3`
	retval=$?
	exec 3>&-
	[ -n "$value" ] || exit 0
	[ "$retval" = "1" ] && exit 0
esac
DIR=install_flash_player_${value}_linux
TARBALL=$DIR.tar.gz
[ -f $TARBALL ] || wget $URL$TARBALL
if [ ! -f $TARBALL ]; then
	echo "Could not download $TARBALL. Exiting."
	exit 1
fi


# Extract
mkdir $DIR
cd $DIR
tar xzf ../$TARBALL

[ -d $DIR ] && mv $DIR/* .
VERSION="$(strings libflashplayer.so | grep ^LNX | sed -e 's/LNX //' -e 's/,/./g')"

# Install files
chmod 755 libflashplayer.so
chown root.root libflashplayer.so
dir=flash-plugin-$VERSION/fs/usr/share/flash
mkdir -p $dir
mv libflashplayer.so $dir

# Sanity Check: Reexport firefox libraries if they don't exist
dir=flash-plugin-$VERSION/fs/usr/lib
mkdir -p $dir
for i in /usr/lib/firefox*/*.so ; do
  	[ -f $i ] && [ -z "`ls /usr/lib/$(basename $i)`" ] && ln -s $i $dir	
done

# Create pseudo package
cat > flash-plugin-$VERSION/receipt <<EOT
PACKAGE="flash-plugin"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="Adobe Flash Player."
WEB_SITE="$WEB_SITE"
DEPENDS="libfirefox curl atk cairo expat fontconfig freetype glib gtk+ libpng \
pango pixman xorg-libICE xorg-libSM xorg-libX11 xorg-libXau xorg-libXcomposite \
xorg-libXcursor xorg-libXdamage xorg-libXdmcp xorg-libXext xorg-libXfixes \
xorg-libXinerama xorg-libXrandr xorg-libXrender xorg-libXt zlib"

post_install()
{
	echo -n "Processing post install commands..."
	if [ -d \$1/var/lib/tazpkg/installed/firefox ] ; then
		ln -s /usr/share/flash/libflashplayer.so \$1/usr/lib/firefox*/plugins
	fi	 
	mkdir -p \$1/usr/lib/mozilla/plugins
	ln -s /usr/share/flash/libflashplayer.so \$1/usr/lib/mozilla/plugins
	status
}

post_remove()
{
	echo -n "Processing post remove commands..."
	if [ -d /var/lib/tazpkg/installed/firefox ] ; then
		rm -f /usr/lib/firefox*/plugins/libflashplayer.so
	fi
	rm -f /usr/lib/mozilla/plugins/libflashplayer.so
	status
}
EOT

# Pack
tazpkg pack flash-plugin-$VERSION

# Install pseudo package
tazpkg install flash-plugin-$VERSION.tazpkg --root=$ROOT
cd ..

# Clean
rm -rf $DIR $TARBALL

