#!/bin/sh -e

PACKAGE="opera"
WEB_SITE="http://www.opera.com/"
CATEGORY="non-free"
DEPENDS=""
URL=https://ftp.opera.com/pub/opera/linux/

ROOT="$1"
[ -d "$ROOT" ] || ROOT=""

if test $(id -u) != 0 ; then
        echo -e "\nYou must be root to run `basename $0`."
        echo -e "Please type 'su' and root password to become super-user.\n"
        exit 0
fi

if [ -d $ROOT/var/lib/tazpkg/installed/$PACKAGE ]; then
	[ -n "$ROOT" ] && exit 1
	tazpkg remove $PACKAGE
	[ -d /var/lib/tazpkg/installed/$PACKAGE ] && exit 1
fi

TMP_DIR=/tmp/get-$PACKAGE-$$-$RANDOM
CUR_DIR=$(pwd)
mkdir -p $TMP_DIR && cd $TMP_DIR

get_releases()
{
	wget -qO- "$URL" | sed 's|.*[Ff]="\([^"/]*\).*|\1|;/[^0-9b]/d' | tac
}

# Download deb
for RELEASE in $@ $(get_releases); do
	FILE=$(wget -O- "$URL$RELEASE/" 2>/dev/null |sed 's|.*[Ff]="\(.*\)".*|\1|;/6.d/!d;q'|sed 's/".*//')
	[ -n "$FILE" ] || continue
	wget $URL$RELEASE/$FILE
	[ -s $FILE ] && break
done

if [ ! -f $FILE ]; then
	cd $CUR_DIR
	rm -rf $TMP_DIR
	echo "Could not download $FILE from $URL. Exiting."
	exit 1
fi

mkdir $PACKAGE
dpkg-deb -e $FILE $PACKAGE/meta
dpkg-deb -x $FILE $PACKAGE/fs
# extracted pkg can be removed: Save RAM
rm -f $FILE
sed '/^Description:/,$!d;s/^Description://' \
	< $PACKAGE/meta/control > $PACKAGE/description.txt

SHORT_DESC="$(sed '/^Description:/!d;s/.*: //' $PACKAGE/meta/control)"
MAINTAINER="$(sed '/^Maintainer:/!d;s/.*: //' $PACKAGE/meta/control)"
VERSION="$(sed '/^Version:/!d;s/.*: //' $PACKAGE/meta/control)"
mv $PACKAGE $PACKAGE-$VERSION
cd $PACKAGE-$VERSION/fs

sed "s|sh$|&\nexport XMODIFIERS=\"@im=none\"|" -i usr/bin/opera

# Create menu
mkdir -p usr/share/applications
cat > usr/share/applications/opera-browser.desktop <<EOT
[Desktop Entry]
Version=1.0
TryExec=opera
Encoding=UTF-8
Name=Opera
Name[af]=opera
Name[eo]=Opero
Name[zu]=I Opera
GenericName=Web browser
GenericName[bs]=Web preglednik
GenericName[de]=Web-Browser
GenericName[eo]=TTT-rigardilo
GenericName[es]=Navegador web
GenericName[et]=Veebibrauser
GenericName[eu]=Web arakatzailea
GenericName[fi]=WWW-selain
GenericName[fr]=Un navigateur web
GenericName[is]=Vafri
GenericName[it]=Browser Web
GenericName[nl]=webbrowser
GenericName[nn]=Nettlesar
GenericName[pt]=Navegador Web
GenericName[pt_BR]=Navegador
GenericName[ro]=Navigator de web
GenericName[sl]=Spletni brskalnik
GenericName[ven]=Buronza ya Webu
GenericName[xh]=Umkhangeli Zincwadi Zokubhaliweyo
GenericName[zu]=Umkhangeli zincwadi we Web
Exec=opera %u
Terminal=false
Categories=Application;Qt;Network;WebBrowser;X-Ximian-Main;X-Ximian-Toplevel
Icon=opera-browser
MimeType=text/html;text/xml;application/xhtml+xml;application/x-mimearchive;application/xml;application/rss+xml;application/rdf+xml;image/svg+xml;image/gif;image/jpeg;image/png;image/x-bmp;image/x-xbm;application/mime
Comment=Web Browser
Type=Application
EOT
cd ../..

cat > $PACKAGE-$VERSION/receipt <<EOT
PACKAGE="$PACKAGE"
VERSION="$VERSION"
CATEGORY="$CATEGORY"
SHORT_DESC="$SHORT_DESC"
MAINTAINER="$MAINTAINER"
DEPENDS="$DEPENDS"
WEB_SITE="$WEB_SITE"
EOT

# Remove unwanted locale
mv $PACKAGE-$VERSION/fs/usr/share/opera/locale $PACKAGE-$VERSION/fs/usr/share/opera/locale-full
mkdir -p $PACKAGE-$VERSION/fs/usr/share/opera/locale 
. /etc/locale.conf
for i in $LANG ${LANG/_/-} ${LANG:0:2} en fr ru pt de zh-cn ; do
	[ -d $PACKAGE-$VERSION/fs/usr/share/opera/locale-full/$i ] &&
	cp -a $PACKAGE-$VERSION/fs/usr/share/opera/locale-full/$i \
		$PACKAGE-$VERSION/fs/usr/share/opera/locale
done
rm -rf $PACKAGE-$VERSION/fs/usr/share/opera/locale-full
rm -rf $PACKAGE-$VERSION/fs/usr/share/pixmaps


# Pack
tazpkg pack $PACKAGE-$VERSION

# Clean to save RAM memory
rm -rf $PACKAGE-$VERSION

# Install pseudo package
tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT
case " $@ " in
*\ --k*) mv $PACKAGE-$VERSION.tazpkg $CUR_DIR ;;
esac

# Clean
cd $CUR_DIR
rm -rf $TMP_DIR

