# SliTaz desktopbox messages.

CHARS_SIZE="64"
NEW_FOLDER_LABEL="Vytvořit novou složku na ploše:"
FOLDER_ENTRY_MSG="Název složky"
NEW_FILE_LABEL="Vytvořit nový soubor na ploše"
FILE_ENTRY_MSG="Název souboru"
ADD_ICON_LABEL="Přidat ikonu na plochu"
DESKTOP_DIALOG_TAZUSB="Uložit komprimovaný systém souborů"
DESKTOP_DIALOG_LABEL="Odhlášení, vypnutí nebo restart počítače"
DESKTOP_LOGOUT_BUTTON="Odhlášení z X windows"
DESKTOP_SHUTDOWN_BUTTON="Vypnout počítač"
DESKTOP_REBOOT_BUTTON="Restartovat počítač"
