#!/bin/sh
# /etc/init.d/connman : Start, stop and restart the connection manager
# on SliTaz, at boot time or with the command line.
#
# To start the connection manager at boot time, just put connman in the
# $RUN_DAEMONS variable of /etc/rcS.conf and configure options with
# /etc/daemons.conf
#
. /etc/init.d/rc.functions
. /etc/daemons.conf

NAME=Connman
DESC="Connection Manager"
DAEMON=connmand
OPTIONS=$CONNMAN_OPTIONS
PIDFILE="$(pidof $DAEMON)"

case "$1" in
  start)
    if [ -n "$PIDFILE" ] ; then
      echo "$NAME is already running."
      exit 1
    fi
    pkill udhcpc 2>/dev/null
    echo -n "Starting $DESC: $NAME... "
    $DAEMON $OPTIONS
    status
    ;;
  stop)
    if [ -z "$PIDFILE" ] ; then
      echo "$NAME is not running."
      exit 1
    fi
    echo -n "Stopping $DESC: $NAME... "
    pkill $DAEMON
    pkill wpa_supplicant
    status
    ;;
  restart)
    if [ -z "$PIDFILE" ] ; then
      echo "$NAME is not running."
      exit 1
    fi
    echo -n "Restarting $DESC: $NAME... "
    pkill $DAEMON &&
    pkill wpa_supplicant &&
    sleep 2 &&
    $DAEMON $OPTIONS
    status
    ;;
  status)
    if [ -n "$PIDFILE" ] ; then
      echo "$NAME is running."  
    else
      echo "$NAME is not running."
    fi  
    ;;
  *)
	printf "\n\033[1mUsage:\033[0m /etc/init.d/%b [start|stop|restart|status]\n" \
		"$(basename $0)"
    exit 1
    ;;
esac

exit 0
