#!/bin/sh 
# Wakoopa is the perfect place to discover software and games online.

PACKAGE="wakoopa"
VERSION="2.0-2"
RPMPKG="$PACKAGE-$VERSION.i386.rpm"
URL="http://apt.wakoopa.com/$RPMPKG"
CUR_DIR=$(pwd)
TEMP_DIR=/tmp/$PACKAGE-$VERSION-$$
ROOT="$1"

# Check if we are root
if test $(id -u) != 0 ; then
    echo -e "\nYou must be root to run `basename $0`."
    echo -e "Please type 'su' and root password to become super-user.\n"
    exit 1
fi

# Avoid reinstall
if [ -d $ROOT/var/lib/tazpkg/installed/$PACKAGE ]; then
    echo -e "\n$PACKAGE package is already installed.\n"
    exit 1
fi

# Create a TEMP_DIR
mkdir $TEMP_DIR
cd $TEMP_DIR

# Download the file
wget $URL 
if [ ! -f $RPMPKG ]; then
    cd $CUR_DIR
    rm -rf $TEMP_DIR
    echo "Could not download $RPMPKG. Exiting."
    exit 1
fi

rpm2cpio $RPMPKG | cpio -dium
# updated desktop menu
sed -i 's/Categories=.*/Categories=Network;/g' $TEMP_DIR/usr/share/applications/wakoopa.desktop 2>/dev/null

# extracted pkg can be removed: Save RAM
rm -rf $RPMPKG

mkdir -p $PACKAGE-$VERSION/fs
mv $TEMP_DIR/usr $PACKAGE-$VERSION/fs

cd $TEMP_DIR

cat > $PACKAGE-$VERSION/receipt << EOT
PACKAGE="$PACKAGE"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="Wakoopa Desktop Tracker."
DEPENDS="gtk+"
WEB_SITE="http://wakoopa.com"
EOT

# Pack
tazpkg pack $PACKAGE-$VERSION

# Clean to save RAM memory
rm -rf $PACKAGE-$VERSION

# Install pseudo package
yes y | tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT

# Clean
cd $CUR_DIR
rm -rf $TEMP_DIR
