#!/bin/sh
# /etc/init.d/ntop : Start, stop and restart ntop daemon on SliTaz, at
# boot time or with the command line.
#
# To start SSH server at boot time, just put ntop in the $RUN_DAEMONS
# variable of /etc/rcS.conf and configure options with /etc/daemons.conf
#
. /etc/init.d/rc.functions


NAME=ntop
DESC="$(_ '%s server' ntop)"
DAEMON=/usr/bin/ntop

HTTP_PORT="3000"
NTOP_USER="ntop"

LOGFILE=/var/log/ntop/ntop.log
PIDFILE=/var/run/ntop.pid

OPTIONS="-w $HTTP_PORT -L -u $NTOP_USER -d"

case "$1" in
  start)
    if active_pidfile $PIDFILE $NAME ; then
      _ '%s is already running.' $NAME
      exit 1
    fi
    # We need to set ntop admin password.
    if [ ! -f /var/ntop/ntop_pw.db ] ; then
      ntop -A || exit
    fi
    action 'Starting %s: %s...' "$DESC" $NAME
    $DAEMON $OPTIONS >> $LOGFILE
    status
    ;;
  stop)
    if ! active_pidfile $PIDFILE $NAME ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Stopping %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE) && rm -f $PIDFILE
    status
    ;;
  restart)
    if ! active_pidfile $PIDFILE $NAME ; then
      _ '%s is not running.' $NAME
      exit 1
    fi
    action 'Restarting %s: %s...' "$DESC" $NAME
    kill $(cat $PIDFILE) && rm -f $PIDFILE
    sleep 2
    $DAEMON $OPTIONS
    status
    ;;
  *)
    emsg "<n><b>$(_ 'Usage:')</b> $0 [start|stop|restart]"
    newline
    exit 1
    ;;
esac

exit 0
