static Key keys[] = {
	{ "&1", XK_ampersand, 1 },
	{ "é2~", XK_eacute, 1 },
	{ "\"3#", XK_quotedbl, 1 },
	{ "'4{", XK_apostrophe, 1 },
	{ "(5[", XK_parenleft, 1 },
	{ "-6|", XK_minus, 1 },
	{ "é7`", XK_egrave, 1 },
	{ "_8\\", XK_underscore, 1 },
	{ "ç9^", XK_cedilla, 1 },
	{ "à0@", XK_agrave, 1 },
	{ ")°]", XK_parenright, 1 },
	{ "=+}", XK_equal, 1 },
	{ "<-", XK_BackSpace, 2 },
	{ 0 }, /* New row */
	{ "->|", XK_Tab, 1 },
	{ "aA", XK_a, 1 },
	{ "zZ", XK_z, 1 },
	{ "eE€", XK_e, 1 },
	{ "rR", XK_r, 1 },
	{ "tT", XK_t, 1 },
	{ "yY", XK_y, 1 },
	{ "uU", XK_u, 1 },
	{ "iI", XK_i, 1 },
	{ "oO", XK_o, 1 },
	{ "pP", XK_p, 1 },
	{ "^", XK_dead_circumflex, 1 },
	{ "$£¤", XK_dollar, 1 },
	{ "Return", XK_Return, 3 },
	{ 0 }, /* New row */
	{ 0, XK_Caps_Lock, 2 },
	{ "qQ", XK_q, 1 },
	{ "sS", XK_s, 1 },
	{ "dD", XK_d, 1 },
	{ "fF", XK_f, 1 },
	{ "gG", XK_g, 1 },
	{ "hH", XK_h, 1 },
	{ "jJ", XK_j, 1 },
	{ "kK", XK_k, 1 },
	{ "lL", XK_l, 1 },
	{ "mM", XK_m, 1 },
	{ "ù%", XK_ugrave, 1 },
	{ "*µ", XK_multiply, 1 },
	{ "\\|", XK_backslash, 1 },
	{ 0 }, /* New row */
	{ 0, XK_Shift_L, 3 },
	{ "wW", XK_w, 1 },
	{ "xX", XK_x, 1 },
	{ "cC", XK_c, 1 },
	{ "vV", XK_v, 1 },
	{ "bB", XK_b, 1 },
	{ "nN", XK_n, 1 },
	{ ",?", XK_comma, 1 },
	{ ";.", XK_semicolon, 1 },
	{ ":/", XK_colon, 1 },
	{ "!§", XK_exclam, 1 },
	{ 0, XK_Shift_R, 2 },
	{ 0 }, /* New row */
	{ "Ctrl", XK_Control_L, 2 },
	{ "Alt", XK_Alt_L, 2 },
	{ "", XK_space, 5 },
	{ "Alt", XK_Alt_R, 2 },
	{ "Ctrl", XK_Control_R, 2 },
	{ "[X]", XK_Cancel, 1},
};

Buttonmod buttonmods[] = {
	{ XK_Shift_L, Button2 },
	{ XK_Alt_L, Button3 },
};

