.TH ppmtoinfo 1 "March  3, 2000"
.SH NAME
ppmtoinfo \- convert a portable pixmap into an Amiga .info file
.SH SYNOPSIS
.B ppmtoinfo
[\-type icontype] [\-floyd|\-fs] [\-map mapfile] [ppmfile] [ppmfile]
.SH DESCRIPTION
This manpage documents briefly the
.B ppmtoinfo
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B ppmtoinfo
is a program that converts portable pixmap (.ppm) files into the
Amiga info format which is used to store icons as.
.SH OPTIONS
.TP
.BI \-type " icontype"
set the type of the icon.
.TP
.B \-floyd, \-fs
Enable Floyd\-Steinberg
.TP
.BI \-map " mapfile"
Use the map file mapfile
.br
.SH ICON TYPES
The
.B \-type
option lets you set the type of the icon you creat.  The parameter
can be any of
.TP
.B appicon
A normal application
.TP
.B device
A device
.TP
.B disk
A disk
.TP
.B drawer
A drawer (directory)
.TP
.B garbage
A garbage can
.TP
.B kick
A kickstart?
.TP
.B project
A project?
.TP
.B tool 
A toolbox?

.SH SEE ALSO
.BR amiwm (1)
.br
.SH AUTHOR
This manual page was written by Jorgen Schaefer <forcer@mindless.com>
for the Debian GNU/Linux system (but may be used by others).
