#!/bin/sh
#
# Get and install non-free Broadcom b43 firmware. The script wil also
# install linux-wireless and b43-fwcutter if needed. Finaly try to
# configure wlan0 interface.
#

DIR="wl_apsta"
VERSION=3.130.20.0
TARBALL=$DIR-$VERSION.o
WGET_URL="http://downloads.openwrt.org/sources/$TARBALL"

# Check if user is root to install.
if test $(id -u) != 0 ; then
	echo -e "\nYou must be root to run `basename $0`."
	echo -e "Please use 'su' and root password to become super-user.\n"
	exit 0
fi

# Avoid reinstall
if [ -d /var/lib/tazpkg/installed/b43legacy-firmware ]; then
	echo -e "\nb43legacy-firmware package is already installed.\n"
	exit 0
fi

# We need drivers, the extractor and tools.
for pkg in linux-wireless b43-fwcutter wireless_tools
do
	if [ ! -d /var/lib/tazpkg/installed/$pkg ]; then
		tazpkg get-install $pkg
	fi
done

# Get files
cd /tmp
wget $WGET_URL || exit 
#tar xjf $TARBALL
#cd $DIR-$VERSION/

# Create pseudo package
mkdir -p b43legacy-firmware-$VERSION/fs/lib/firmware
b43-fwcutter -w "b43legacy-firmware-$VERSION/fs/lib/firmware" wl_apsta-3.130.20.0.o

# Creat receipt
cat > b43legacy-firmware-$VERSION/receipt <<EOT
PACKAGE="b43legacy-firmware"
VERSION="$VERSION"
CATEGORY="non-free"
SHORT_DESC="Broadcom b43legacy firmware."
DEPENDS="b43-fwcutter"
WEB_SITE="http://downloads.openwrt.org/"
EOT

# Pack
tazpkg pack b43legacy-firmware-$VERSION

# Install pseudo package
tazpkg install b43legacy-firmware-$VERSION.tazpkg

# Clean
cd /tmp
rm -rf $TARBALL $DIR-$VERSION

# Load b43legacy module
echo "Loading module: b43legacy..."
modprobe b43legacy
sleep 1

# Configure /etc/network.conf and start connexion
sed -i s/'WIFI="no"'/'WIFI="yes"'/ /etc/network.conf
. /etc/network.conf

iwconfig $WIFI_INTERFACE essid $ESSID
echo "Starting udhcpc client on: $WIFI_INTERFACE... "
/sbin/udhcpc -b -i $WIFI_INTERFACE \
	-p /var/run/udhcpc.$WIFI_INTERFACE.pid

